packages:
  - packages/*
  - third-party/common/ts

catalog:
  '@aws-sdk/client-dynamodb': 3.984.0
  '@aws-sdk/client-lambda': 3.984.0
  '@aws-sdk/client-ssm': 3.984.0
  '@aws-sdk/lib-dynamodb': 3.984.0
  '@eslint/js': 9.39.2
  '@lightweight-clients/jikan-api-lightweight-client': 4.0.2
  '@types/aws-lambda': 8.10.160
  '@types/node': 25.2.1
  '@vitest/coverage-v8': 4.0.18
  '@vitest/ui': 4.0.18
  aws-cdk: 2.1105.0
  aws-cdk-lib: 2.237.1
  aws-sdk-client-mock: 4.1.0
  cdk-lambda-llrt: 0.1.4
  constructs: 10.4.5
  cross-env: 10.1.0
  eslint: 9.39.2
  eslint-plugin-simple-import-sort: 12.1.1
  jiti: 2.6.1
  knip: 5.83.0
  npm-run-all: 4.1.5
  typescript: 5.9.3
  typescript-eslint: 8.54.0
  vitest: 4.0.18

nodeLinker: hoisted

onlyBuiltDependencies:
  - aws-sdk
  - esbuild
